mystr = "This is a string"
print(len(mystr))
print(mystr)
print(mystr[4])
print(mystr[2:7])
print(mystr[2:9:2])
print(mystr[::])
print(mystr[::-1])
print(mystr.endswith("ing"))
print(mystr.count("i"))
print(mystr.capitalize())
print(mystr.upper())
print(mystr.lower())
